services:
  traefik:
    # https://hub.docker.com/_/traefik
    image: traefik:v3.1.4
    restart: always
    # Enables the web UI and tells Traefik to listen to docker
    environment:
      - TZ=Asia/Bangkok
    command:
      - --configFile=/root/.config/traefik.yaml
    labels:
      # Accessing dashboard via traefik
      - traefik.enable=true
      - traefik.http.services.traefik.loadBalancer.server.port=8080
      - traefik.http.routers.traefik.rule=Host(`traefik.<YOUR_BASE_URL>`)
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.entrypoints=websecure
      - traefik.http.routers.traefik.tls.certresolver=production
      - traefik.http.routers.traefik.middlewares=auth-traefik
      - traefik.http.middlewares.auth-traefik.basicauth.usersfile=/root/.config/.htpasswd
    ports:
      # The HTTP port
      - 80:80
      - 443:443
      # The Dashboard
      # - 8080:8080
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      # For config
      - ${PWD}/config:/root/.config/
      # For Files provider
      # - ${PWD}/files:/root/files/
      # For logging
      - ${PWD}/logs:/root/logs/
      # For SSL
      - ${PWD}/cert:/root/cert/
    networks:
      - default

networks:
  default: